language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script: nosetests
sudo: required
dist: precise
deploy:
  provider: pypi
  user: __token__
  password:
    secure: iock6SDyVCusWm/L5fVUg5qaibGCfhO+lEzc/6iALI/0ZlmfElWF9ijC6h2kkylnbLjm0+x0AelqTEV0YhrkmPuroGH6t/WOcinOHKpxVoy2695/JA3U2F6RrbcDeb55srxZrTRvGHdxASQm4i4A2Ty6zjci0ekU1i11mvBtoO4=
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    python: 3.5
    condition: $TRAVIS_PYTHON_VERSION = "3.5"