language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script: nosetests
sudo: required
dist: precise
deploy:
  provider: pypi
  user: $USER
  password: $PASS
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "3.4"
env:
  global:
  - secure: "XJ8JnWU4iprVkIYb+3KcUWe2VLQjI275chcnWUB6ZCJlE64OGWbvqtzbn67ARICqTqK8julSCO//wOcqHeOXNcTqZ4yHzxGBQXIHBlEXWp6xVTdnD8zl+F/S5g05GcNNAdJyfxW83z3Eha7QUTHbmYfLw/Ev9u85+5My00zZz0U="
  - secure: "N04bNRIgSTEvLP1QFKK4LPuS99l95UbdAt7yL1C0o/ijayRNPVnchyvJjYeqmG3HhlYpBFuS416DuIsftR/rMn/Lozz6aQ6WqdPB/hqnz+0wiETf8WPuh+iqAeCNGL4kiHTv8xZaAvH4Gkqn2SEIKgCbGFzEQekG1JF54giZSdM="
