language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script: nosetests
sudo: required
dist: precise
deploy:
  provider: pypi
  user: __token__
  password:
    secure: SvJl5/5vWaiyrP1gGRTZFnMBvRhzGZunhvgY0eTKakC7fY1mgkD93qfeMt/Uzfb2KBOGvvbYqLqN4Pyx/KYfeHBQ5AOtNVFPYyQwL3JrruLZI+V71yExntcWOgvwUW6VWoRP+OvPZBs+5eP5r211G4K1LLR/2J6/WsWYZZ46pSk=
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    python: 3.5
    condition: $TRAVIS_PYTHON_VERSION = "3.5"