language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script: nosetests
sudo: required
dist: precise
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ZUKSnUENEPkwSyNz5VpjN8MGVH0p8Eiu1SRH9dN1redaqQyjBn2O7YStXCx5PXMbEg3zgzyu3QXorIvph6kF0nl3SBFkbBQ+9UNaVtPiDY9ubS85iH8p4XvmVinAh+4kN4P4MbK7Pq0HdvpD5tNvmLmJdah00evk18rkkCSH/fs=
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    python: 3.5
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
