language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script: nosetests
sudo: required
dist: precise
deploy:
  provider: pypi
  user: __token__
  password:
    secure: rpfi3n/+oKepeZ9qfVMC1A0QnMZUNTnflIo/jAwmm1PoYBv0Y31LPcNeMos7VKDo56R5Zq2RscYL1C1oiytxL9CTUnYNdeoUu0cf7G+eiK0UzR2LsPLTmmIFFFOhtUF66vjetkXSAHCHCRwL+74u5Hd0qWfZgbkJfxNm7i4UCbc=
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "3.5"