name: mangopay2-python-sdk-ci

on:
  push:
    branches:
      # push on master branch
      - master
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          pip install -r requirements/base.txt
          pip install -r requirements/development.txt
      - name: Run tests
        run: |
          python -m unittest discover
